### ISSUE TITLE
Error when adding new venue: "Oops, the parent ID does not match the hierarchy neighbourhood_id."

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-boundaryissues#253]
When trying to add a new venue record in Park City, Utah, Boundary Issues gave me the following error message:

`"Oops, the parent ID does not match the hierarchy neighbourhood_id."`

**Steps to reproduce:**

1. From the [Add Venue page](https://whosonfirst.mapzen.com/boundaryissues/venue/), add a "Venue name" of "El Chubasco"
2. In the "Address" field, enter: 
    "1890 Bonanza Dr. Suite 115
      Park City, UT 84060"
3. Click the "find it on the map" button
4. In the "Tags" field, enter "Mexican, Restaurant, Food, Drinks"
5. Click the "Add Venue" button

Tagging @thisisaaronland, as this relates to the Python hierarchy building.

**Comment by thisisaaronland** [comment]
@dphiffer - this is definitely a bug in the BI logic.

When I query for that lat,lon against pip.mz I get back a list of places, none of which are neighbourhoods and when I filter for neighbourhoods I get no results:

http://pip.mapzen.com/?latitude=40.661367&longitude=-111.500959
http://pip.mapzen.com/?latitude=40.661367&longitude=-111.500959&placetype=neighbourhood

The same is true when calling the API:

```
curl -X GET 'https://whosonfirst-api.mapzen.com/?method=whosonfirst.places.getByLatLon&api_key=mapzen-xxxxxx&latitude=40.661367&longitude=-111.500959&placetype=neighbourhood&format=json'

{
  "places": [],
  "stat": "ok"
}
```

Your code is calling the BI wrapper for doing PIP stuff and getting back a response with an incorrect parent ID (based on placetype):

```
{
    "hierarchy": [
        {
            "continent_id": 102191575,
            "country_id": 85633793,
            "county_id": 102083555,
            "locality_id": 101727553,
            "region_id": 85688567
        }
    ],
    "ok": 1,
    "parents": [
        {
            "Deprecated": false,
            "Id": 101727553,
            "Name": "Park City",
            "Offset": -1,
            "Placetype": "locality",
            "Superseded": false
        }
    ],
    "stat": "ok"
}
```

**Comment by thisisaaronland** [comment]
The problem is here:

https://github.com/whosonfirst/whosonfirst-www-boundaryissues/blob/master/services/geojson-server/wof-geojson-server.py#L122

Or specifically in the request parameters that you are passing to the `get_reverse_geocoded` method. The front-end JS code is passing in `placetype=neighbourhood` rather than `venue`. You are reverse geocoding a venue whose _parent_ would be a neighbourhood.

```
parents = mapzen.whosonfirst.pip.utils.get_reverse_geocoded(40.661367, -111.500959, "neighbourhood", pip_server=pip_server)
[{u'Name': u'Park City', u'Deprecated': False, u'Superseded': False, u'Placetype': u'locality', u'Offset': -1, u'Id': 101727553}]

parents = mapzen.whosonfirst.pip.utils.get_reverse_geocoded(40.661367, -111.500959, "venue", pip_server=pip_server)
print parents
[]
```

**Comment by thisisaaronland** [comment]
Oh, I see what the larger problem is: The PIP server will return an `Invalid placetype` error if you request a placetype that hasn't been indexed, specifically venues.

@dphiffer - In advance of other changes your code will need to account for venues by _not_filtering by placetype and then checking the results for a neighbourhood record.

**Comment by thisisaaronland** [comment]
Current thinking is that the problem has two parts:

1. The reverse geocoding logic is passing the incorrect placetype:

https://github.com/whosonfirst/whosonfirst-www-boundaryissues/blob/master/www/javascript/mapzen.whosonfirst.boundaryissues.venue.js#L108-L115

2. The validation code is being overly specific

https://github.com/whosonfirst/whosonfirst-www-boundaryissues/blob/master/www/javascript/mapzen.whosonfirst.boundaryissues.venue.js#L560

In advance of a proper `mz.wof.placetypes.js` library that can be queried for the parents of a placetype, the most expedient thing to do is just update the current check with additional placetypes defined here:

https://github.com/whosonfirst/whosonfirst-placetypes/blob/master/placetypes/venue.json#L5

**Comment by dphiffer** [comment]
Thanks @stepps00, this should be fixed now. Let me know if you see that message again!

**Comment by dphiffer** [comment]
Hmm, further testing makes me think I haven't fixed this after all.

**Comment by stepps00** [comment]
@dphiffer - confirming the last comment - it looks like there is still an issue adding this record to WOF via Boundary Issues. The error message is now:

`Oops, the parent ID is invalid.`

Can file a new issue if this is an unrelated problem.

**Comment by dphiffer** [comment]
Yeah, I just deployed _another_ fix. This time I think things are good, but maybe I'll let you weigh in before I close this again, @stepps00.

**Comment by dphiffer** [comment]
Hrm... Pretty sure I still haven't fixed this yet. It's getting closer tho.

**Comment by dphiffer** [comment]
Ok now _this time_ it should be fixed.

**Comment by stepps00** [comment]
@dphiffer - Looks like this issue is fixed! I followed the steps in my initial comment and was able to save the record without an error. Added a second venue in a nearby location and again, no error.

**Comment by dphiffer** [comment]
Hooray!! \o/
